#pragma once

#include <Windows.h>


HINSTANCE hInst; //Instance handle

WCHAR szTitle[MAX_PATH];
WCHAR szWindowClass[MAX_PATH];
WCHAR szPrintString[MAX_PATH];
UCHAR szPtdiagVersion[MAX_PATH];
UCHAR szPtdiagVersionShort[MAX_PATH / 2];

//May be wrong type here
WCHAR szInputFileHex[MAX_PATH];
WCHAR szInputFileVBF[MAX_PATH];
WCHAR szInputFileVBF2[MAX_PATH];
WCHAR szGenericInputFile[MAX_PATH];
WCHAR szGenericSecondaryFile[MAX_PATH];
WCHAR szGenericSecondaryFileVBF[MAX_PATH];
WCHAR szLookupTableFile[MAX_PATH];
WCHAR szConfigPath[MAX_PATH];
WCHAR szPIDListPath[MAX_PATH];
WCHAR szDMRListPath[MAX_PATH];
WCHAR szConfigPathOSC[MAX_PATH];
WCHAR szListPathOSC[MAX_PATH];
WCHAR szGenericSavePath[MAX_PATH];
WCHAR szLoadScanFile[MAX_PATH];
WCHAR szLoadScanFileMyCANIC[MAX_PATH];
WCHAR szDTCFileMode6Data[MAX_PATH];
WCHAR szTranslatedTableNumRows[MAX_PATH];
WCHAR szTranslatedTableNumCols[MAX_PATH];
WCHAR szTranslatedTableStartAddress[MAX_PATH];
WCHAR szFirmwareRev[MAX_PATH];
WCHAR szPassThruToolType[MAX_PATH];

HWND hWndMain;
HWND hWndDialog1;
HWND hWndGenLog;
HWND hWndUsageWin;
HWND hWndTextPop1;
HWND hWndTextPop2;
HWND hWndTextPop3;
HWND hWndCANDebug;

//Global flags
USHORT usSecondInstance;
USHORT usThirdInstance;
USHORT usMyCANICFlag;
USHORT usRunBikeAtStartup;
USHORT usAlternateResponseOffset1;
USHORT usBuildVersion;
USHORT usProtocol;
USHORT usComlevel;
USHORT usGlobalTestMode;
USHORT usSTPasswordEntry1;
USHORT usSTPasswordEntry2;
USHORT usSTPasswordEntry3;
USHORT usSTPasswordEntry4;
USHORT usSTPasswordEntry5Diesel;
USHORT usEnableDieselResetFunctions;
USHORT usFLITestMode;
USHORT usOverrideDefaultSettings;
USHORT usDataRate;
USHORT usCaptureDataWarning;
USHORT usContinuousCapture;
USHORT usLogMilliseconds;
USHORT usDataDisplaySwap;
USHORT usDataDisplayWide;
USHORT usAutoStartMode;
USHORT usDataCapWindowVisible;
USHORT usExtraDataWindowVisible;
USHORT usMinMaxDataWindowVisible;
USHORT usMinMaxDataWindowState;
USHORT usPIDSelectionWindowVisible;
USHORT usDMRSelectionWindowVisible;
USHORT usOutputSelection;
USHORT usDMRByteOrderMotorola;
USHORT usDisableLowVoltageWarning;
USHORT usSampleRate;
USHORT usNumInitParms;
USHORT usP558ECMSwapPlantMode;
USHORT usShowBlackIceStatus;
USHORT usGlobalTestMode;
USHORT usLogOtherError;
USHORT usProgThreadTestMode;
USHORT usUploadThreadTestMode;
USHORT usMonitorTestMode;
USHORT usDTCTestMode;
USHORT usSpecialTestMode1;
USHORT usManualEPATSInstall;
USHORT usETCTestMode;
USHORT usFLITestMode;
USHORT usFaultInjTestMode;
USHORT usDataAcqPowerCycle;
USHORT usForceNoVIDSave;
USHORT usDGB1SimulationMode;
USHORT usDGB1SimulationVLS;
USHORT usLogPokeTableTestData;
USHORT usEraseRegionOverride;
USHORT usVBFToolTestMode;
USHORT usCCPTestMode;
USHORT usCCPSimulationMode;
USHORT usTridUpdateTestMode;
USHORT usHEVFuelTestMode;
USHORT usCD33xClusterEmulation;
USHORT usFuelEconEmulation;
USHORT usAdaptiveCruiseEmulation;
USHORT usFuelEconOBDIITestMode;
USHORT usFuelEconOBDIISimulation;
USHORT usMyCANICStressTest1;
USHORT usBypassCRCMismatchErrors;
USHORT usAllowFTCFunctionsWindow;
USHORT usMEMReadTestMode;
USHORT usEONVTestMode;
USHORT usTimeStampDebugMode;
USHORT usShowCGEA_PATS_Msgs_Only;
USHORT usKOEO_6R_Plant_Test;
USHORT usShow11and29bitCANData;
USHORT usProgStressTestMode;
USHORT usSnakeTestMode;
USHORT usMAFSensorTesting;
USHORT usPCVTestSwitch;
USHORT usAutoOSCEnableTestMode;
USHORT usCRCTestModeSwitch;
USHORT usFileBrowserTestMode;
USHORT us10msChronoTestMode;
USHORT usCLSDataAcquisitionEnable;
USHORT usCLSDataAcquisitionEnable2;
USHORT usProCalUploadTestMode;
USHORT usFuelPrimeTestMode;
USHORT usCodedAccess11TestMode;
USHORT usSBLPowerCycleTestMode;
USHORT usDieselOSCCustomOverride;
USHORT usVCTTestMode;
USHORT usSBLDownloadTestMode;
USHORT usP558ECMSwapPlantMode;
USHORT usTimeStampTestMode;
USHORT usSession40TestMode;
USHORT usSecureProgrammingMode;
USHORT usDownloadTestLoop;
USHORT usSocketTestMode;
USHORT usConvertApplinkEnable;
USHORT usConvertSmogCheckData;
USHORT usTransAdaptTestMode;
USHORT usMode06TestMode;
USHORT usProgrammingLoopMode;
USHORT usUreaSensorTestMode;
USHORT usSNLockTestMode;
USHORT usDRDConversionTestMode;
USHORT usAutoOBDIIReadTestMode;
USHORT usAutoBootCodeUpdate;
USHORT usAlternatorRampTestMode;
USHORT usOverrideDefaultSettings;
USHORT usShowKeyStrokes;
USHORT usEnableExtraSecurityFunctions;
USHORT usDisplayStandardPopups;
USHORT usProgModeLockoutMode1;
USHORT usEOLVIDProgramStressTestMode;
USHORT wWindowAdjustFlag;

static USHORT ALT_RATING1_OFFSET;
static USHORT PA_ID_OFFSET;
static USHORT ALT_RATING2_OFFSET;
static USHORT COOLING_FAN_OFFSET;
static USHORT SNOW_PLOW_OFFSET;
static USHORT AGS_OFFSET;
static USHORT AAT_OFFSET;
static USHORT EOC_OFFSET;
static USHORT AEIS_OFFSET;
static USHORT EOTC_OFFSET;
static USHORT MEFC_OFFSET;
static USHORT VIN_OFFSET;
static USHORT ASTERISK_OFFSET;
static USHORT OCTANE_ADJ_OFFSET;
static USHORT OCT_RATING_OFFSET;
static USHORT SPEED_LIMIT_OFFSET;
static USHORT TIRE_OFFSET;
static USHORT AXLE_OFFSET;
static USHORT LOW_RANGE_OFFSET;
static USHORT TCASE_OFFSET;
static USHORT SPEED_CTL_OFFSET;
static USHORT SPEED_SRCE_OFFSET;
static USHORT SC_TYPE_OFFSET;
static USHORT DRIVETRAIN_OFFSET;
static USHORT WHEEL_BASE_OFFSET;
static USHORT SHUTDOWN_OFFSET;
static USHORT KEYLESS_OFFSE;
static USHORT SST_OFFSET;
static USHORT DRIVE_AXLE_OFFSET;
static USHORT ASL_OFFSET;
static USHORT TMM_OFFSET;
static USHORT TOW_HAUL_OFFSET;
static USHORT RING_GEAR_OFFSET;
static USHORT OPTIONAL_ECU_OFFSET1;
static USHORT OPTIONAL_ECU_OFFSET2;
static USHORT KEYLESS_OFFSET;

UCHAR bGlobalSecurityBytesInitFile1[12];
UCHAR bGlobalSecurityBytesInitFile2[12];


ULONG ulActiveChannelId;